# Generated by Django 3.2 on 2021-05-27 12:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dokumentu', models.IntegerField(default=0)),
                ('name', models.CharField(default='Document_name', max_length=255)),
                ('typ_pliku', models.CharField(default='*', max_length=200)),
                ('sciezka_do_pliku', models.CharField(default='/', max_length=200)),
                ('udostepnienie', models.BooleanField(default=False)),
                ('myfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'txt', 'jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Dysk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dysku', models.IntegerField(default=0)),
                ('rozmiar_calkowity', models.IntegerField(default=0)),
                ('rozmiar_zajety', models.IntegerField(default=0)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_katalogu', models.IntegerField(default=0)),
                ('nazwa', models.CharField(max_length=200)),
                ('sciezka_do_katalogu', models.CharField(max_length=200)),
                ('id_dysku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysk.dysk')),
                ('id_katalogu_nadrzednego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dysk.katalog')),
            ],
        ),
        migrations.CreateModel(
            name='Widok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_widoku', models.IntegerField(default=0)),
                ('nazwa', models.CharField(default='*', max_length=255)),
                ('tresc', models.TextField(default='Text sample')),
            ],
        ),
        migrations.CreateModel(
            name='SchowekPlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_schowka', models.IntegerField(default=0)),
                ('id_pliku', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dysk.document')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pliku', models.IntegerField(default=0)),
                ('nazwa', models.CharField(max_length=200)),
                ('typ_pliku', models.CharField(max_length=200)),
                ('sciezka_do_pliku', models.CharField(max_length=200)),
                ('id_katalogu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysk.katalog')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='id_katalogu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dysk.katalog'),
        ),
    ]
