# Generated by Django 3.2 on 2021-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='udostepniony',
            field=models.BooleanField(default=False),
        ),
    ]
