# Generated by Django 3.2 on 2021-04-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0002_auto_20210429_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
    ]
