# Generated by Django 3.2 on 2021-05-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0002_document_udostepniony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='udostepniony',
            new_name='udostepnienie',
        ),
    ]
