# Generated by Django 3.2 on 2021-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0003_delete_uzytkownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='id_dysku',
            field=models.IntegerField(default=0),
        ),
    ]
