# Generated by Django 3.2 on 2021-05-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0004_plik_id_dysku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plik',
            old_name='id_dysku',
            new_name='id_d',
        ),
    ]
