# Generated by Django 3.2 on 2021-05-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0005_katalog_id_katalogu_nadrzednego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='id_katalogu_nadrzednego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysk.katalog'),
        ),
    ]
