# Generated by Django 3.2 on 2021-05-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0014_katalog_id_katalogu_nadrzednego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='id_katalogu_nadrzednego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dysk.katalog'),
        ),
    ]
