# Generated by Django 3.2 on 2021-05-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0015_auto_20210509_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id_dysku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dysk.dysk'),
            preserve_default=False,
        ),
    ]
