# Generated by Django 3.2 on 2021-05-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0005_rename_id_dysku_plik_id_d'),
        ('dysk', '0015_alter_katalog_id_katalogu_nadrzednego'),
    ]

    operations = [
    ]
