# Generated by Django 3.2 on 2021-05-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0016_merge_20210517_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plik',
            name='id_d',
        ),
        migrations.AddField(
            model_name='document',
            name='id_dokumentu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='id_katalogu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dysk.katalog'),
        ),
        migrations.AddField(
            model_name='document',
            name='sciezka_do_pliku',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='typ_pliku',
            field=models.CharField(default='*', max_length=200),
        ),
    ]
