# Generated by Django 3.2 on 2021-05-22 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0017_auto_20210517_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='myfile',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'txt', 'jpg', 'png'])]),
        ),
    ]
