# Generated by Django 3.2 on 2021-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0018_auto_20210522_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='widok',
            name='id_widoku',
            field=models.IntegerField(default=0),
        ),
    ]
