# Generated by Django 3.2 on 2021-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0019_widok_id_widoku'),
    ]

    operations = [
        migrations.AddField(
            model_name='widok',
            name='nazwa',
            field=models.CharField(default='*', max_length=255),
        ),
        migrations.AlterField(
            model_name='widok',
            name='tresc',
            field=models.TextField(default='Text sample'),
        ),
    ]
