# Generated by Django 3.2 on 2021-05-23 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dysk', '0020_auto_20210522_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchowekPlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_schowka', models.IntegerField(default=0)),
                ('id_pliku', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dysk.document')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
