# Generated by Django 3.2 on 2021-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0021_schowekplik'),
    ]

    operations = [
        migrations.AddField(
            model_name='plik',
            name='udostepniony',
            field=models.BooleanField(default=False),
        ),
    ]
