# Generated by Django 3.2 on 2021-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysk', '0022_plik_udostepniony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plik',
            name='udostepniony',
        ),
        migrations.AddField(
            model_name='document',
            name='udostepniony',
            field=models.BooleanField(default=False),
        ),
    ]
